---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: idam
  namespace: idam
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.idam-api: glob:aat-*
    fluxcd.io/tag.idam-web-public: glob:aat-*
    fluxcd.io/tag.idam-web-admin: glob:aat-*
spec:
  releaseName: idam
  timeout: 900
  forceUpgrade: true
  rollback:
    enable: true
    force: true
  rollback:
    enable: true
  chart:
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    name: idam
    version: 0.1.2
  values:
    global:
      environment: demo
    idam-api:
      java:
        image: hmctspublic.azurecr.io/idam/api:latest
    idam-web-public:
      java:
        image: hmctspublic.azurecr.io/idam/web-public:latest
    idam-web-admin:
      java:
        image: hmctspublic.azurecr.io/idam/web-admin:latest
