apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-reply-urls
  namespace: auto-reply-url
spec:
  replicas: 1
  selector:
    matchLabels:
      name: auto-reply-urls
  template:
    metadata:
      labels:
        name: auto-reply-urls
    spec:
      serviceAccountName: auto-reply-urls
      containers:
        - name: auto-reply-urls
          image: hmctspublic.azurecr.io/timj/auto-reply-urls:11
          command:
          - auto-reply-urls
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "auto-reply-urls"
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auto-reply-urls-creds
                  key: azure_client_id
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auto-reply-urls-creds
                  key: azure_client_secret
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: auto-reply-urls-creds
                  key: azure_tenant_id
            - name: OBJECT_ID
              value: "39e76f8b-ba1c-4338-8a07-04f55d09495a"
