version: 1
commandUpdated:
  generators:
    - command: kustomize build --load_restrictor none .
  updaters:
    - containerImage:
        command: >-
          (yq --version || (wget -O /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/3.2.0/yq_linux_amd64" && chmod +x /usr/local/bin/yq)) &&
          echo $FLUX_WL_NAME &&
          echo $FLUX_WL_NS &&
          echo $FLUX_CONTAINER &&
          echo $FLUX_TAG &&
          echo $FLUX_IMG &&
          file_name=../../namespaces/$FLUX_WL_NS/$FLUX_WL_NAME/sandbox.yaml &&
          touch $file_name &&
          yq w -i $file_name 'apiVersion' helm.fluxcd.io/v1 &&
          yq w -i $file_name kind HelmRelease &&
          yq w -i $file_name metadata.name $FLUX_WL_NAME &&
          yq w -i $file_name metadata.namespace $FLUX_WL_NS &&
          yq w -i $file_name spec.values.java.image "$FLUX_IMG:$FLUX_TAG" &&
          cat $file_name &&
          git status &&
          git add $file_name &&
          git commit -m "explicit commit" &&
          git push &&
          pwd &&
          cat ../../name/test