---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: draft-store-service
  namespace: rpe
spec:
  values:
    java:
      image: hmctspublic.azurecr.io/draft-store/service:prod-b2e188e4
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rpe-service-auth-provider
  namespace: rpe
spec:
  values:
    java:
      image: hmctspublic.azurecr.io/rpe/service-auth-provider:prod-02409d06
