---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ecm-consumer
  namespace: ethos
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.java: glob:prod-*
spec:
  releaseName: ecm-consumer
  rollback:
    enable: true
    retry: true
  chart:
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    name: ecm-consumer
    version: 0.1.3
  values:
    java:
      replicas: 2
      useInterpodAntiAffinity: true
      image: hmctspublic.azurecr.io/ethos/ecm-consumer:prod-5e0bb255
    global:
      environment: ldata
      tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
      enableKeyVaults: true
