---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: admin
spec:
  values:
    git:
      path: "k8s/sandbox/common,k8s/sandbox/cluster-01,k8s/sandbox/cluster-01-overlay,k8s/common,k8s/sandbox/common-overlay"
      label: "sandbox-cluster-01"
      branch: "testkustomize"
