---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: draft-store-service
  namespace: rpe
spec:
  values:
    java:
      image: hmctspublic.azurecr.io/draft-store/service:prod-586cf20c
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rpe-service-auth-provider
  namespace: rpe
spec:
  values:
    java:
      image: hmctspublic.azurecr.io/rpe/service-auth-provider:prod-cd811b15
