apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../namespaces/rpe/namespace.yaml
- ../../../namespaces/rpe/draft-store-service/draft-store-service.yaml
- ../../../namespaces/rpe/s2s/rpe-service-auth-provider.yaml
patchesStrategicMerge:
#rpe patches
- ../../../namespaces/rpe/draft-store-service/sandbox.yaml
- ../../../namespaces/rpe/sandbox.yaml