apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../namespaces/rpe/
  - ../../../namespaces/rpe/draft-store
  - ../../../namespaces/rpe/service-auth-provider

patchesStrategicMerge:
  #rpe patches
  - flux-patch.yaml
  - ../../../namespaces/rpe/draft-store/sandbox.yaml