apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../namespaces/rpe/
  - ../../../namespaces/rpe/draft-store
  - ../../../namespaces/rpe/service-auth-provider

patchesStrategicMerge:
  #rpe patches
  - ../../../namespaces/rpe/draft-store/sandbox.yaml
patches:
  - path: sandbox.yaml
    target:
      kind: HelmRelease