---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cmc-demo-full
  namespace: money-claims
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.java: 'glob:prod-*'
    repository.fluxcd.io/cmc-citizen-frontend: cmc-citizen-frontend.nodejs.image
    filter.fluxcd.io/cmc-citizen-frontend: glob:prod-*
    repository.fluxcd.io/cmc-claim-store: cmc-claim-store.java.image
    filter.fluxcd.io/cmc-claim-store: glob:prod-*
    repository.fluxcd.io/rpe-feature-toggle-api: rpe-feature-toggle-api.java.image
    filter.fluxcd.io/rpe-feature-toggle-api: glob:prod-*

spec:
  releaseName: cmc-demo-full
  timeout: 900
  forceUpgrade: true
  rollback:
    enable: true
    force: true
  chart:
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    name: cmc
    version: 1.1.7
  values:
    global:
      devMode: true
      idamApiUrl: https://idam-api.demo.platform.hmcts.net
      idamWebUrl: https://idam-web-public.demo.platform.hmcts.net
      cmcFrontendUrl: cmc-citizen-frontend-full.demo.platform.hmcts.net
      cmcBackendUrl: "http://cmc-demo-full-claim-store"
      draftStoreUrl: "http://draft-store-service-demo.service.core-compute-demo.internal"
      s2sAuthUrl: "http://rpe-service-auth-provider-demo.service.core-compute-demo.internal"
      pdfServiceUrl: "http://cmc-pdf-service-demo.service.core-compute-demo.internal"
      paymentUrl: "http://payment-api-demo.service.core-compute-demo.internal"
      feesUrl: "http://fees-register-api-demo.service.core-compute-demo.internal"
      sendLetterUrl: "http://rpe-send-letter-service-demo.service.core-compute-demo.internal"
      documentManagementUrl: "http://dm-store-demo.service.core-compute-demo.internal"
      dgAssemblyUrl: "http://dg-docassembly-demo.service.core-compute-demo.internal"
      ccdCaseDataApiUrl: "http://ccd-data-store-api-demo.service.core-compute-demo.internal"
      togglesUrl: "http://rpe-feature-toggle-api-demo.service.core-compute-demo.internal"
      postgresqlHost: "cmc-demo.postgres.database.azure.com"

    ### CMC SERVICES ###
    cmc-claim-store:
      java:
        releaseNameOverride: "cmc-demo-full-claim-store"
        image: hmctspublic.azurecr.io/cmc/claim-store:prod-d76f3e9b
        secrets:
          IDAM_S2S_AUTH_TOTP_SECRET:
            secretRef: claim-store-s2s-secret
            key: key
        environment:
          FRONTEND_BASE_URL: "https://{{ .Values.global.cmcFrontendUrl }}"
          RESPOND_TO_CLAIM_URL: "https://{{ .Values.global.cmcFrontendUrl }}/first-contact/start"
          CMC_DB_CONNECTION_OPTIONS: '?ssl=true&sslmode=require'
          DOC_ASSEMBLY_TEMPLATEID: CV-CMC-GOR-ENG-0004-1.docx
          DOC_ASSEMBLY_JUDGETEMPLATEID: CV-CMC-GOR-ENG-00219-1.docx

    cmc-citizen-frontend:
      nodejs:
        releaseNameOverride: "cmc-demo-cmc-citizen-frontend"
        image: hmctspublic.azurecr.io/cmc/citizen-frontend:prod-10de70df
        ingressHost: "{{ .Values.global.cmcFrontendUrl }}"
        secrets:
          IDAM_S2S_TOTP_SECRET:
            secretRef: cmc-s2s-secret
            key: key
        environment:
          FEATURE_TOGGLES_API_URL: "{{ .Values.global.togglesUrl }}"
          CLAIM_STORE_URL: "{{ .Values.global.cmcBackendUrl }}"

      idam-pr:
        api:
          url: "https://idam-api.demo.platform.hmcts.net"
        web_public:
          url: "https://idam-web-public.demo.platform.hmcts.net"
        service:
          redirect_uri: "https://{{ .Values.global.cmcFrontendUrl }}/receiver"
