---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: div-pfe
  namespace: divorce
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.nodejs: glob:pr-684-*
spec:
  releaseName: div-pfe
  rollback:
    enable: true
    retry: true
  chart:
#    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
#    name: div-pfe
#    version: 1.1.3
    git: https://github.com/hmcts/div-petitioner-frontend
    ref: demo
    path: charts/div-pfe
  values:
    nodejs:
      replicas: 2
      useInterpodAntiAffinity: true
      image: hmctspublic.azurecr.io/div/pfe:pr-684-8884dcea
      ingressHost: petitioner-frontend-aks.aat.platform.hmcts.net
      environment:
        PUBLIC_HOSTNAME: https://petitioner-frontend-aks.aat.platform.hmcts.net
        DECREE_NISI_FRONTEND_URL: https://decree-nisi-aks.aat.platform.hmcts.net
    global:
      environment: aat
      tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
      enableKeyVaults: true
