name: Flux PR automation checks

# yamllint disable-line
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Flux automation tests
        run: ./tests/flux-automation.sh ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}

---

name: Flux push automation checks

# yamllint disable-line
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Flux automation tests
        run: ./tests/flux-automation.sh ${{ github.event.before }} ${{ github.event.after }}
